name: Deploy to server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull from Github repo
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.USER }}@${{secrets.IP }} << EOF
            cd /var/www/ci_cd-test
            sudo git pull origin master
          EOF

      - name: Deploy via PM2
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.USER }}@${{secrets.IP }} << EOF
            cd /var/www/ci_cd-test
            sudo npm run build
            pm2 restart 0 --silent
          EOF